services:
  app:
    build: .
    container_name: glyfs_app
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - DATABASE_URL=postgres://glyfs:glyfs@db:5432/glyfs?sslmode=disable
      - PORT=8080
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg16
    container_name: glyfs_db
    environment:
      - POSTGRES_DB=glyfs
      - POSTGRES_USER=glyfs
      - POSTGRES_PASSWORD=glyfs
    ports:
      - "5433:5432"
    volumes:
      - glyfs-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glyfs -d glyfs"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  glyfs-db-data:
